/**
 * stickers-data.js
 * ix/iy = initial position as fraction of canvas width/height
 * rot   = initial rotation degrees
 * surface = 'wall' | 'floor'  (visual hint only, stickers go on bg image)
 */

const STICKERS_DATA = [
  // ── VIBE ──────────────────────────────────────
  {
    id: 'shenghuoyin',
    category: 'vibe',
    surface: 'wall',           // left wall area
    name: '生活印诗机',
    subtitle: 'vibe',
    organization: '个人',
    sticker: 'assets/stickers/shenghuoyin.PNG',
    tags: ['AIGC', '24H 黑客松', 'Top 15', '小红书'],
    description: '从现实生活中收集文字碎片进行创作的 AI 拼字产品。用手机拍摄招牌、包装、路牌中的字母，OCR 识别后沉淀为个人"生活字母库"，再由 AI 根据情绪关键词生成短诗。',
    role: '独立设计 · 体验设计实习（小红书）',
    period: '2026.05',
    metrics: [
      { value: '24H', label: '黑客松独立完成' },
      { value: 'Top15', label: '全站作品排名' },
    ],
    demoType: 'iframe',
    demoUrl: 'https://lifescribe-beta.vercel.app/',
    demoAspect: 'phone',
    longImages: [
      'assets/projects-webp/shenghuoyin/long/1.webp',
      'assets/projects-webp/shenghuoyin/long/2.webp',
      'assets/projects-webp/shenghuoyin/long/3.webp',
      'assets/projects-webp/shenghuoyin/long/4.webp',
      'assets/projects-webp/shenghuoyin/long/5.webp',
      'assets/projects-webp/shenghuoyin/long/6.webp',
    ],
    longImageCaptions: [
      { title: '把日常观察变成创作素材', body: '生活印诗机从街景、包装和路牌中采集字母，让平常容易忽略的文字成为个人创作的起点。用户无需先准备一套素材，就可以从身边开始记录。' },
      { title: '用“生活是自己的勋章”建立产品概念', body: '这一页把项目的核心想法落到生活场景：街景、物件和个人感受都可以被重新连接。讲述时可以说明，产品希望让记录不止于收藏，而能继续转化为表达。' },
      { title: '让收集到的字母持续可用', body: '字母库沉淀用户在不同时间和地点拍摄得到的素材，并支持之后重新发现和组合。它把一次性的拍摄变成可持续积累的个人内容资产。' },
      { title: '从一个具体字母开始', body: '用户可以围绕眼前物件上的字母直接发起创作，不需要预先整理素材或填写复杂信息。这个入口降低了开始成本，让记录融入日常动作。' },
      { title: '组合、编辑并保存作品', body: '收集到的字母可以被组合成可浏览的视觉作品，并继续调整和编辑。设计重点是让素材从字母库自然进入创作流程，而不是停留在列表里。' },
      { title: '让 AI 根据情绪完成表达', body: '用户输入当下感受后，AI 结合已收集的字母生成短诗；生成结果可以保存和分享。AI 承接素材与情绪之间的转译，让个人积累最终形成可传达的作品。' },
    ],
    heroEmoji: '🌿',
    ix: 0.10, iy: 0.10, rot: -7,
    size: 'large',
  },
  {
    id: 'tashi',
    category: 'vibe',
    surface: 'wall',           // right wall area
    name: '它石智航官网',
    subtitle: 'vibe',
    organization: 'Tars',
    sticker: 'assets/stickers/tashi.PNG',
    tags: ['Vibe Coding', '品牌官网', '前端开发'],
    description: '为智能硬件品牌「它石智航」vibe coding 的官网首页 demo，探索沉浸式科技叙事与品牌视觉的结合。全程使用 Cursor 辅助完成从设计到前端实现的完整链路。',
    role: '独立设计 & 开发',
    period: '2026.05',
    metrics: [
      { value: '全栈', label: 'Vibe Coding 实现' },
    ],
    demoType: 'iframe',
    demoUrl: 'https://tarsweb.pages.dev/',
    heroEmoji: '🏢',
    ix: 0.68, iy: 0.08, rot: 9,
    size: 'normal',
  },

  // ── PORTFOLIO ──────────────────────────────────
  {
    id: 'zhihu-circle-ai',
    category: 'portfolio',
    surface: 'wall',
    name: '知乎圈子 AI',
    subtitle: 'AI 社区管理',
    organization: '知乎',
    sticker: 'assets/stickers/zhihu-circle-ai.png',
    tags: ['AI', '社区产品', '小红书笔试题'],
    description: '负责知乎圈子 AI 管理员项目的整体 UX/UI 设计，并参与定义 AI 管理员头像生成 Skill 与 Bot 回复风格。',
    role: '产品体验设计 · 笔试项目',
    period: '2026.09',
    metrics: [],
    demoType: null, demoUrl: null,
    longImages: [
      'assets/projects-webp/zhihu-circle-ai/long/1.webp',
      'assets/projects-webp/zhihu-circle-ai/long/2.webp',
      'assets/projects-webp/zhihu-circle-ai/long/3.webp',
      'assets/projects-webp/zhihu-circle-ai/long/4.webp',
      'assets/projects-webp/zhihu-circle-ai/long/5.webp',
      'assets/projects-webp/zhihu-circle-ai/long/6.webp',
      'assets/projects-webp/zhihu-circle-ai/long/7.webp',
      'assets/projects-webp/zhihu-circle-ai/long/8.webp',
      'assets/projects-webp/zhihu-circle-ai/long/9.webp',
    ],
    longImageCaptions: [
      { title: '为知乎圈子设计 AI 管理员', body: '封面呈现 AI 加入圈子的产品方向、项目角色与时间。项目聚焦如何让 AI 协助圈子运营，同时让主理人理解、配置并掌握 AI 的参与方式。' },
      { title: '从运营负担与互动不足找到机会', body: '主理人需要持续巡检和处理内容，而发帖之后也缺少及时、真实的互动。设计机会在于让 AI 承担重复的社区维护工作，并保留主理人对规则和处理结果的控制权。' },
      { title: '先建立可控机制，再定义社区行为', body: '整体策略分为两侧：主理人侧提供配置和处理记录，圈子侧定义 AI 回复与角色形象。先让管理过程可设置、可查看，再把 AI 的参与方式放进具体社区语境中。' },
      { title: '让主理人知道 AI 能做什么', body: '首次进入时通过引导卡解释 AI 管理员的职责和能力边界，并在圈子入口保留提示，帮助主理人随时找到功能。重点是先建立预期，再让用户决定是否开启。' },
      { title: '把管理能力交给主理人配置', body: '主理人可以维护 AI 管理员资料，并按需开启评论、优质想法加精和低质想法处理等能力。将能力拆成可理解的开关，便于不同圈子依据自身规则选择使用范围。' },
      { title: '让每次处理都有记录可查', body: '处理记录归档加精、置底和移除等操作，同时展示 AI 的判断依据，并提供撤销或清理入口。这样主理人既能了解 AI 做过什么，也能在结果不合适时及时纠正。' },
      { title: '让 AI 形象贴合圈子气质', body: '根据圈子的主题、简介和表达风格生成管理员形象与资料，使 AI 不只是统一模板里的工具角色。形象生成与资料配置共同帮助主理人塑造符合社区语境的 AI 管理员。' },
      { title: '让 AI 以明确身份参与讨论', body: 'AI 评论结合圈子信息、内容情绪和交流意图组织回复，并清楚标识 AI 身份及内容边界。设计目标是补充讨论互动，同时避免用户误认为回复来自真实成员。' },
      { title: '以可配置、可追溯作为设计原则', body: '项目将管理配置、处理记录和社区互动串成完整体验，强调 AI 能力可控制、过程可追溯、角色能融入圈子。项目仍在开发阶段，实际效果需要在上线后继续验证。' },
    ],
    heroEmoji: '🤖',
    ix: 0.30, iy: 0.36, rot: -6,
    size: 'normal',
  },
  {
    id: 'gather',
    category: 'vibe',
    surface: 'wall',
    name: 'Gather',
    subtitle: '生活记忆收集',
    organization: '个人',
    sticker: 'assets/stickers/gather.png',
    tags: ['Vibe', '交互原型', '小红书笔试题'],
    description: '一款帮助人们收集家庭记忆、并将散落片段重新编织成故事的移动端体验。通过贴纸化的互动方式整理照片与记忆，让日常素材成为可分享、可传承的叙事。',
    role: '产品设计 · 笔试项目',
    period: '2026.09',
    metrics: [],
    demoType: 'iframe',
    demoUrl: 'https://jdingaiy.github.io/gathertime-interaction-demo/',
    demoAspect: 'phone',
    longImages: [
      'assets/projects-webp/gather/long/1.webp',
      'assets/projects-webp/gather/long/2.webp',
      'assets/projects-webp/gather/long/3.webp',
      'assets/projects-webp/gather/long/4.webp',
      'assets/projects-webp/gather/long/5.webp',
      'assets/projects-webp/gather/long/6.webp',
      'assets/projects-webp/gather/long/7.webp',
      'assets/projects-webp/gather/long/8.webp',
      'assets/projects-webp/gather/long/9.webp',
      'assets/projects-webp/gather/long/10.webp',
      'assets/projects-webp/gather/long/11.webp',
    ],
    longImageCaptions: [
      { title: '把生活片段整理成家庭记忆', body: 'Gather 从家庭照片和物件出发，帮助用户把散落的生活片段整理成可以持续补充的记忆。产品希望记录过程像分享和收集一样轻松，而不是一次性完成厚重的回忆录。' },
      { title: '降低开始记录的心理负担', body: '很多家庭希望留下人生故事，却常常不知道从哪里开始；繁琐的整理要求也容易让记录搁置。项目因此把重点放在更自然的入口，让一段记忆可以从手边的照片或物件开始。' },
      { title: '从一件物品开启记录', body: '用户可以拍摄一件物品或选择一张照片，逐步收集可回听、可阅读的家庭记忆。每次只记录一个片段，能让长期项目拆解成更容易完成的小步骤。' },
      { title: '让家人一起参与讲述', body: '记忆讲述者、发起者和共创家人都可以加入记录，不同代际能够留下自己的视角并补充故事。共同参与让家庭记忆不只由一个人整理，也让内容在交流中不断丰富。' },
      { title: '围绕照片和物件展开对话', body: '照片与物件为家庭交流提供具体线索，帮助家人回忆并保存共同经历中的细节。界面围绕这些素材组织故事，让记忆更容易被唤起和继续讲述。' },
      { title: '把回忆录拆成随时可做的小记录', body: '产品将“写一本回忆录”拆解为可以随时开始的轻量记录，减少持续整理的压力。用户可以先完成一个片段，再决定是否继续补充相关故事。' },
      { title: '用 AI 辅助整理素材', body: 'AI 能识别物件、修复老照片、转写口述并整理故事，减少准备和录入工作。它负责辅助处理素材，记忆的内容与讲述仍来自家庭成员本身。' },
      { title: '让记忆在首页可浏览', body: '首页以物件和照片构成个人记忆空间，用户点开条目即可查看标题、时间及相关故事。视觉上让素材成为入口，方便家庭成员回到某段具体记忆。' },
      { title: '让照片和物件更容易入库', body: '拍摄流程支持收藏和扫描；物件图片可抠图，老照片也可以选择修复，降低素材准备成本。用户能按当下需求处理素材，不必先完成复杂编辑。' },
      { title: '用口述代替逐项填写', body: '用户可以直接录音或开始访谈，通过说话留下记忆，而不必逐项填写文字信息。这样的输入方式更接近日常讲述，也能帮助不习惯写作的家庭成员参与。' },
      { title: '让访谈自然沉淀为故事', body: '访谈既可以记录自然对话，也可以由 AI 围绕物件提出问题；结束后内容会整理成记忆详情并归入合集。记录、整理和回看形成连续流程，让一次交流最终成为可保存的家庭故事。' },
    ],
    heroEmoji: '🧩',
    ix: 0.82, iy: 0.28, rot: 7,
    size: 'normal',
  },
  {
    id: 'ikea-aigc',
    category: 'portfolio',
    surface: 'wall',
    name: '宜家 AIGC 生产引擎',
    subtitle: '0-1MVP',
    organization: 'IKEA',
    sticker: 'assets/stickers/ikea-aigc.PNG',
    tags: ['AIGC', 'B2B', '效率工具', '宜家'],
    description: '针对海量长尾商品视频缺失、外包成本高昂问题，设计以线性叙事流与人机协同为核心的 AI 视频生产工具。结构化 Prompt 和预设封装植入视觉护栏，实现端到端规模化商业级生产。',
    role: 'UX 实习生 · 宜家中国创新中心 · 独立主导',
    period: '2025.12',
    metrics: [
      { value: '↑80%', label: '视频产出效率' },
      { value: '20万', label: '年节省外包成本' },
      { value: '↑50%', label: '视频覆盖率' },
    ],
    demoType: null, demoUrl: null,
    heroEmoji: '🤖',
    ix: 0.36, iy: 0.07, rot: 3,
    size: 'normal',
    longImages: [
      'assets/projects-webp/ikea-aigc/long/0.webp',
      'assets/projects-webp/ikea-aigc/long/1.webp',
      'assets/projects-webp/ikea-aigc/long/2.webp',
      'assets/projects-webp/ikea-aigc/long/3.webp',
      'assets/projects-webp/ikea-aigc/long/4.webp',
      'assets/projects-webp/ikea-aigc/long/5.webp',
      'assets/projects-webp/ikea-aigc/long/6.webp',
      'assets/projects-webp/ikea-aigc/long/7.webp',
      'assets/projects-webp/ikea-aigc/long/8.webp',
      'assets/projects-webp/ikea-aigc/long/9.webp',
      'assets/projects-webp/ikea-aigc/long/10.webp',
      'assets/projects-webp/ikea-aigc/long/11.webp',
    ],
    longImageCaptions: [
      { title: '把商品视频生产串成完整工作流', body: '平台将商品素材、视频生成和内容交付整合到一个工作台，面向长尾商品的规模化生产。重点不是单独展示生成能力，而是让生成结果能够顺畅进入审核和交付。' },
      { title: '补足长尾商品的视频覆盖', body: '大量长尾商品缺少可用视频，依赖人工制作难以同时满足效率和成本要求。业务背景由此指向自动化生产，但生成质量必须符合商业内容的使用标准。' },
      { title: '评估模型在生产中的可用性', body: '模型对比不仅关注画面质量，也关注提示稳定性和后期处理成本。评估结果帮助确定哪些环节需要产品能力兜底，避免把模型输出直接等同于可交付内容。' },
      { title: '用工作台补上流程断点', body: '自建工作台连接 CMS 资产、视频生成、编辑和审核，承接通用生成工具难以覆盖的业务流程。资产和任务集中后，运营人员可以在同一链路里完成生产与管理。' },
      { title: '梳理运营人员的实际任务路径', body: '流程从查找素材开始，经过生成、挑选，最终完成内容交付。按真实任务顺序分析每一步的信息和决策，可以定位反复切换工具、等待和筛选造成的时间损耗。' },
      { title: '围绕生产能力比较同类工具', body: '竞品分析聚焦素材管理、生成控制、结果编辑和版本追溯等能力。对比的目的在于识别商业生产需要的完整支持，而非只比较生成按钮和模型数量。' },
      { title: '以接入、控制和编辑组织方案', body: '设计策略围绕既有资产接入、生成过程可控和结果轻量编辑展开。三个环节共同保持生产流程连贯，让运营人员既能复用素材，也能对生成结果做必要调整。' },
      { title: '按任务顺序呈现素材与结果', body: '界面将素材、生成参数和预览按操作顺序组织，减少来回切换。运营人员可以在查看结果时继续调整参数，快速迭代到满足业务要求的版本。' },
      { title: '提供多种任务起点', body: '用户可以从已有商品素材、CMS 资产或创作入口开始，并进入统一工作台继续操作。不同来源的任务最终汇入相同的生成与交付流程，降低入口割裂。' },
      { title: '把模型参数转成可理解的控制项', body: '界面将模型能力转译为更易理解的选项，同时保留提示词编辑能力。这样既能帮助普通运营人员快速开始，也为需要精细控制的任务保留调整空间。' },
      { title: '让成片回到内容资产流程', body: '用户可以挑选和管理生成片段，再将成品交回既有内容资产流程。输出与原有交付体系衔接，减少生成结果成为孤立文件的情况。' },
      { title: '用 MVP 指标验证效率变化', body: 'MVP 记录单条视频处理时长和素材选择耗时，用于观察工作流优化是否降低了操作成本。规模化生产、质量稳定性和长期业务效果仍需要后续继续验证。' },
    ],
  },
  {
    id: 'ikea-guide',
    category: 'portfolio',
    surface: 'floor',          // floor area
    name: '宜家虚拟导购助手',
    subtitle: '0-1MVP',
    organization: 'IKEA',
    sticker: 'assets/stickers/ikea-guide.PNG',
    tags: ['对话 UI', 'RAG', '情感化设计', '宜家'],
    description: '聚焦门店高 SKU 区域无员工值守导致的顾客静默流失痛点，设计基于 RAG 的虚拟导购，提供参数对比、货架导航等拟人化选品支持，引入情感化微交互激励数据回流。',
    role: 'UX 实习生 · 宜家中国创新中心 · 独立主导',
    period: '2025.09 – 2025.10',
    metrics: [
      { value: '89%', label: '结构化问答准确率' },
      { value: '↑15%', label: '顾客停留时长' },
      { value: '↑12%', label: '锅具品类销量' },
    ],
    demoType: null, demoUrl: null,
    heroEmoji: '🛒',
    ix: 0.54, iy: 0.62, rot: -12,
    size: 'tiny',
    longImages: [
      'assets/projects-webp/ikea-guide/long/1.webp',
      'assets/projects-webp/ikea-guide/long/2.webp',
      'assets/projects-webp/ikea-guide/long/3.webp',
      'assets/projects-webp/ikea-guide/long/4.webp',
      'assets/projects-webp/ikea-guide/long/5.webp',
      'assets/projects-webp/ikea-guide/long/6.webp',
      'assets/projects-webp/ikea-guide/long/7.webp',
      'assets/projects-webp/ikea-guide/long/8.webp',
      'assets/projects-webp/ikea-guide/long/9.webp',
      'assets/projects-webp/ikea-guide/long/10.webp',
      'assets/projects-webp/ikea-guide/long/11.webp',
      'assets/projects-webp/ikea-guide/long/12.webp',
      'assets/projects-webp/ikea-guide/long/13.webp',
      'assets/projects-webp/ikea-guide/long/14.webp',
    ],
    longImageCaptions: [
      { title: '在门店选购中提供 AI 导购支持', body: '项目面向线下选购场景，为顾客提供产品信息和决策支持。AI 导购需要适应门店即时咨询的节奏，让顾客在货架旁也能快速获得有用答案。' },
      { title: '找到高 SKU 场景中的服务缺口', body: '高 SKU 商品区的信息复杂，顾客在没有员工及时协助时容易中断选购。设计需要降低查找与理解产品信息的成本，并及时回应顾客当下的疑问。' },
      { title: '沿着决策旅程确定介入时机', body: '用户旅程覆盖发现、了解、考虑、比较和决策几个阶段，用于定位 AI 导购能够提供帮助的时刻。这样可以让功能围绕顾客任务出现，而不是把所有能力堆在一个入口里。' },
      { title: '明确体验需要解决的问题', body: '体验目标聚焦商品信息更容易发现、对话过程更顺畅，以及产品差异更容易理解。目标为后续入口设计、问答流程和比较能力提供了统一判断标准。' },
      { title: '将数字服务放入真实门店环境', body: '方案结合门店动线、屏幕位置和扫码设备，规划顾客如何发现并使用服务。设备与界面需要互相配合，让顾客在购物现场能自然开始交互。' },
      { title: '让顾客清楚如何开始提问', body: '首屏说明 AI 可以提供的帮助，并给出清楚的唤起入口。顾客能够快速理解服务用途，也能判断哪些产品问题适合交给 AI 咨询。' },
      { title: '为语音交互提供明确反馈', body: '语音流程覆盖开始、识别、暂停和继续等状态，让顾客知道系统正在聆听、处理还是等待。清楚的状态反馈有助于减少门店环境下的误操作和不确定感。' },
      { title: '形成从提问到回答的闭环', body: '交互链路从发起对话开始，经过问题理解和信息组织，最终呈现回答。流程围绕门店即时咨询设计，帮助顾客尽快回到商品了解和选购任务。' },
      { title: '让设备能力与界面信息一致', body: '摄像头和扫码设备与界面协同工作，说明设备位置、识别范围及结果反馈。把硬件能力讲清楚，能帮助顾客理解如何操作以及系统可以识别什么。' },
      { title: '用商品内容解释具体问题', body: '商品卡片、详情、二维码和常见问题共同承接产品解释。信息按照顾客的咨询逐步展开，避免只给出抽象回答却无法继续了解商品。' },
      { title: '帮助顾客比较商品差异', body: '并列展示商品信息，支持顾客围绕自身需求快速比较产品差异。比较结果把参数和选择理由放在一起，辅助顾客缩小选项范围。' },
      { title: '承接门店信息与下一步决策', body: '门店位置、优惠信息和延伸问题帮助顾客完成后续决策。服务不仅回答产品问题，也提供与现场购物相关的下一步信息。' },
      { title: '区分目标估算与实际验证', body: '页面记录了体验目标和业务变化的上线后估算。讲述时需要把预期指标与已验证结果区分开，避免将目标或估算表述为已经证实的因果效果。' },
      { title: '根据反馈调整首页信息层级', body: '用户反馈指出入口容易被看成广告、使用频次偏低，因此首页需要更清楚地说明服务价值并加强内容承接。改版围绕入口理解和后续使用路径进行调整。' },
    ],
  },
  // 部分项目拆在 js/stickers-private.js（原 NDA 拆分，全站公开后等价）。

  // ── STUDIO ─────────────────────────────────────
  {
    id: 'hci-studio',
    category: 'studio',
    surface: 'floor',
    name: 'Crown',
    subtitle: 'HCI研究',
    organization: '个人',
    sticker: 'assets/stickers/hci-studio.PNG',
    tags: ['HCI', 'YOLOv8', '机器学习', '论文一作'],
    description: '结合 YOLOv8 视觉算法与机器学习，研究实时响应人群密度并进行形态演变的具身智能折叠装置。第一作者论文收录于 2025 计算性设计学术论坛。',
    role: '研究者 · 第一作者 · 天津大学数字化设计工作室',
    period: '2024.10 – 2025.06',
    metrics: [
      { value: '论文', label: '第一作者 · 2025 计算性设计论坛' },
    ],
    demoType: null, demoUrl: null,
    heroEmoji: '🏗️',
    ix: 0.76, iy: 0.58, rot: -8,
    size: 'normal',
    longImages: [
      'assets/projects/hci-studio/long/01.webp',
      'assets/projects/hci-studio/long/02.webp',
      'assets/projects/hci-studio/long/03.webp',
      'assets/projects/hci-studio/long/04.webp',
      'assets/projects/hci-studio/long/05.webp',
      'assets/projects/hci-studio/long/06.webp',
      'assets/projects/hci-studio/long/07.webp',
      'assets/projects/hci-studio/long/08.webp',
      'assets/projects/hci-studio/long/09.webp',
      'assets/projects/hci-studio/long/10.webp',
      'assets/projects/hci-studio/long/11.webp',
    ],
    longImageCaptions: [
      { title: '让公共装置回应人群活动', body: 'Crown 通过可折叠、可变化的公共装置回应城市人群活动，探索空间形态与人的行为如何相互影响。研究将互动机制转化为能够被观察和体验的实体空间。' },
      { title: '从行为研究推导折叠形态', body: '项目结合人群行为研究与折叠形态分析，推导装置的构成逻辑和互动方式。研究阶段把人的活动需求转成结构与形态设计的依据。' },
      { title: '用模型验证机械结构', body: '模型尺度阶段用于验证连杆、驱动路径和结构连接，为实体原型建立机械基础。通过早期结构推演，可以在投入真实尺度制作前发现运动关系中的问题。' },
      { title: '检验装置的运动状态', body: '原型呈现装置展开、升起和收拢等状态，用于检验结构运动是否成立，以及形态变化如何影响周边空间。实体验证将概念方案转化为可观察的运动过程。' },
      { title: '依据场地确定装置落位', body: '场地分析结合天津城市广场环境、人流与活动特征，确定装置的落位方式。装置设计需要回应真实场地中的人群流线和公共活动，而不是孤立地考虑造型。' },
      { title: '拆解真实尺度的建造关系', body: '结构方案拆解基础、框架和膜结构，并呈现施工构造与安装关系。真实尺度的结构说明让设计从形态概念继续落实到可建造的空间装置。' },
      { title: '说明装置与城市空间的关系', body: '剖面呈现装置、广场、地下设备空间和人群活动之间的空间关系。通过剖面可以说明装置如何落在场地中，并与不同高度和使用区域发生联系。' },
      { title: '把感知数据转化为形态变化', body: '交互流程连接传感器采集、行为分析和装置形态输出，展示数据如何驱动实体变化。研究重点是让感知与响应构成可解释的完整链路。' },
      { title: '识别并分析人群流动', body: '行人检测、轨迹追踪和流动分析为人群行为分类提供数据基础。视觉算法把现场活动转为后续交互可使用的信息，支持装置理解不同的人群状态。' },
      { title: '根据活动类型切换空间状态', body: '装置依据人群活动类型在开放、聚集和收拢等状态之间变化。形态不再是固定背景，而成为对周围活动做出回应的动态空间界面。' },
      { title: '让日常叙事连接人和城市', body: '日常叙事展示装置如何随时间和人群变化，并将空间状态与城市生活、公共活动联系起来。项目最终关注的是装置如何成为人们感知和使用公共空间的一部分。' },
    ],
  },

  // ── ILLUSTRATION ───────────────────────────────
];

if (typeof window !== 'undefined') window.STICKERS_DATA = STICKERS_DATA;
