/**
 * stickers-private.js — 原「完整密码可见」的 NDA 项目数据。
 * 2026.07 起全站公开，此文件与 stickers-data.js 等价，仅为保留文件拆分。
 */
STICKERS_DATA.push(
  {
    id: 'sixteen',
    category: 'portfolio',
    surface: 'wall',
    name: 'AI 健康打卡APP',
    subtitle: '产品迭代',
    organization: '小红书',
    sticker: 'assets/stickers/sixteen.PNG',
    tags: ['C 端', 'AI', '健康', '小红书'],
    description: '针对小红书健康打卡场景，重构日历信息架构，设计 AI 驱动的智能打卡引导流程。通过情感化贴纸激励机制与个性化反馈，显著提升用户打卡渗透率与持续参与度。',
    role: 'UX 实习生 · 小红书 · 独立主导',
    period: '2026.02',
    metrics: [
      { value: '↑25%', label: '打卡渗透率' },
      { value: '95%+', label: '贴纸视觉可用率' },
    ],
    demoType: null, demoUrl: null,
    longImages: [
      'assets/projects-webp/sixteen/long/1.webp',
      'assets/projects-webp/sixteen/long/2.webp',
      'assets/projects-webp/sixteen/long/3.webp',
      'assets/projects-webp/sixteen/long/4.webp',
      'assets/projects-webp/sixteen/long/5.webp',
      'assets/projects-webp/sixteen/long/6.webp',
      'assets/projects-webp/sixteen/long/7.webp',
      'assets/projects-webp/sixteen/long/8.webp',
      'assets/projects-webp/sixteen/long/9.webp',
      'assets/projects-webp/sixteen/long/10.webp',
    ],
    longImageCaptions: [
      { title: '把健康建议连接到每日行动', body: '这次体验迭代希望将健康记录和 AI 建议进一步连接到日常执行。设计关注的不只是给出建议，还要帮助用户知道接下来可以做什么。' },
      { title: '让用户知道今天从哪里开始', body: '产品已有健康记录与建议能力，但用户仍可能不知道今天该采取哪项行动。界面需要把抽象建议变成清晰、可开始的任务。' },
      { title: '定位记录到执行之间的断点', body: '用户反馈与行为数据指向记录、计划查看和实际执行之间的转化问题。梳理这些断点有助于确定体验迭代应连接哪些环节，而不是只增加新的功能入口。' },
      { title: '串起建议、日历和训练动作', body: '方案通过统一 AI 入口、日历化每日安排和训练动作拆解，承接从健康建议到实际执行的过程。用户可以从咨询得到方向，再在日程中看到具体安排。' },
      { title: '用连续对话承接健康问题', body: '分散入口整合为连续对话，让 AI 能够承接饮食、训练和计划相关问题。对话保留上下文，减少用户在不同功能之间重复描述的成本。' },
      { title: '把建议放进可执行的日程', body: 'AI 生成的建议进入每日安排，用户能在日历中看到下一步行动。建议由此不再停留在聊天回复里，而是成为可查看和安排的任务。' },
      { title: '按时间管理每日健康任务', body: '日历按时间展示饮食和运动任务，并区分计划前与计划进行中的状态。清楚的时间结构帮助用户理解当日节奏，也便于追踪任务进度。' },
      { title: '支持查看和编辑任务细节', body: '详情页补充饮食和训练相关信息，并支持编辑任务内容与安排。用户可以根据实际情况调整计划，让 AI 建议更贴近个人生活节奏。' },
      { title: '将长期目标拆成训练阶段', body: '长期训练计划被拆解为阶段目标、执行动作、频率和注意事项。结构化呈现让较长周期的计划更容易理解，也便于逐步落实和回顾。' },
      { title: '明确 MVP 后续验证指标', body: '总结页列出 AI 建议承接、计划查看与训练执行等后续验证方向。它们用于评估体验是否真正推动了行动，仍需要在后续版本中通过数据继续验证。' },
    ],
    heroEmoji: '📅',
    ix: 0.44, iy: 0.32, rot: -5,
    size: 'tiny',
  },
  {
    id: 'nova-chat',
    category: 'portfolio',
    surface: 'wall',
    name: '小红书风险感知平台',
    subtitle: '0-1MVP',
    organization: '小红书',
    sticker: 'assets/stickers/nova-chat.PNG',
    tags: ['B2B', 'Agent', '中台产品', '小红书'],
    description: '将搜索巡检、风险研判及处置报告等核心运营能力解构为标准化 Skills，依托 Nova Chat 构建 7×24 风险运营专家 Agent，解决跨平台操作零散和技能沉淀难的痛点。',
    role: 'UX 实习生（小红书）· 独立主导 MVP 设计',
    period: '2026.03',
    metrics: [
      { value: '↓40%', label: '核心操作链路时长' },
      { value: '↓30%', label: '员工上手培训时间' },
    ],
    demoType: null, demoUrl: null,
    longImages: [
      'assets/projects-webp/nova-chat/long/1.webp',
      'assets/projects-webp/nova-chat/long/2.webp',
      'assets/projects-webp/nova-chat/long/3.webp',
      'assets/projects-webp/nova-chat/long/4.webp',
      'assets/projects-webp/nova-chat/long/5.webp',
      'assets/projects-webp/nova-chat/long/6.webp',
      'assets/projects-webp/nova-chat/long/7.webp',
      'assets/projects-webp/nova-chat/long/8.webp',
      'assets/projects-webp/nova-chat/long/9.webp',
    ],
    longImageCaptions: [
      { title: '把风险运营工作集中到 Agent 工作台', body: 'Nova Chat 面向风险运营，将风险发现、研判、处置和报告能力整合到统一工作台。目标是让运营人员在一个连续工作流中调用能力并跟进任务。' },
      { title: '减少跨系统切换和信息整理', body: '现有流程横跨多个系统，查找信息、切换工具和整理材料挤压了风险判断与决策时间。项目从这些操作成本出发，重新组织运营工作入口。' },
      { title: '用 Skills 沉淀专业任务能力', body: '既有业务能力被封装为任务型 Skills，再由统一对话入口承接运营工作。标准化封装便于用户按任务调用，也为后续复用和扩展建立基础。' },
      { title: '帮助用户开始并续接任务', body: '欢迎页提供推荐任务和历史会话，帮助新用户快速开始，也支持回到未完成的工作。首页围绕任务启动和任务续接组织信息。' },
      { title: '覆盖对话中的关键状态和产物', body: '对话流程呈现输入、加载和回答状态，并承接附件、事件链接与文档输出。状态反馈帮助用户了解系统进展，产物能力则让工作结果能继续使用。' },
      { title: '在同一流程完成多类风险工作', body: '专项巡检、线索研判和协同处置等工作可以在同一对话流程中衔接。用户不必为每种任务重新寻找入口，Agent 根据具体目标调用对应能力。' },
      { title: '将分析结果整理为结构化报告', body: '系统把风险数据和分析结果汇总为结构化报告，减少人工复制和排版。报告承接对话中的工作成果，便于后续沟通和决策。' },
      { title: '让任务进度可创建、追踪和回看', body: '任务管理能力支持运营人员在对话中创建任务、追踪处理状态并回看历史进展。对话与任务状态结合，使持续性工作更容易管理。' },
      { title: '围绕效率和体验设定验证方向', body: 'MVP 总结呈现处理时长、系统跳转次数和满意度等评估方向，并标明设计贡献。指标需要在真实使用中持续验证，才能判断工作台是否改善了运营效率。' },
    ],
    heroEmoji: '🛡️',
    ix: 0.14, iy: 0.48, rot: 6,
    size: 'small',
  },
);
